export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Head } from "./Head";
export { default as Analytics } from "./Analytics";
export { default as Custom404 } from "./Custom404";
export { default as BrazilMap } from "./BrazilMap";
export { default as BrazilGeojson } from "./BrazilGeojson";
export { default as Popup } from "./Popup";
export { default as YearButtons } from "./YearButtons";
